south_park/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from apps.home import views as home
from apps.services import views as services
from apps.about import views as about
from apps.gallery import views as gallery
from apps.contact import views as contact
from apps.blog import views as blog


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", home.home_page, name="home_page"),
    path("services/", services.services_page, name="services_page"),
    path("about/", about.about_page, name="about_page"),
    path("gallery/", gallery.gallery_page, name="gallery_page"),
    path("blog/", blog.blog_page, name="blog_page"),
    path("post/<int:id>/", blog.post_view, name="post_view"),
    path("comment/send/<int:id>/", blog.send_comment, name="send_comment"),
    path("contact/", contact.contact_page, name="contact_page"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/about/models.py
from django.db import models


class AboutPage(models.Model):
    title = models.CharField(max_length=32, default="О Нас")
    description = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to="images/about/")


class Review(models.Model):
    image = models.ImageField(upload_to="images/about/reviews/")
    review = models.CharField(max_length=255, default="")
    name = models.CharField(max_length=32)
    position = models.CharField(max_length=32)


class Contacts(models.Model):
    phone = models.CharField(max_length=16, default="")
    email = models.EmailField()
    address = models.CharField(max_length=255, default="")
    wa = models.CharField(max_length=64, default="")
    tg = models.CharField(max_length=64, default="")

apps/blog/models.py
from django.db import models


class BlogPage(models.Model):
    title = models.CharField(max_length=32, default="Блог")
    description = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to="images/blog/main/")

    def __str__(self) -> str:
        return self.title


class Author(models.Model):
    full_name = models.CharField(max_length=128)
    image = models.ImageField(upload_to="images/blog/authors/")
    description = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.full_name


class Tag(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    image = models.ImageField(upload_to="images/blog/")
    date = models.DateField()
    title = models.CharField(max_length=32)
    description = models.TextField()

    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    iamge = models.ImageField(upload_to="images/blog/commentators_images/", blank=True, null=True)
    email = models.EmailField()
    name = models.CharField(max_length=64)
    site = models.URLField(blank=True, null=True)
    message = models.CharField(max_length=1024)

    def __str__(self) -> str:
        return self.name

apps/contact/models.py
from django.db import models


class ContactPage(models.Model):
    title = models.CharField(max_length=32, default="Контакты")
    description = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to="images/contact/")

apps/gallery/models.py
from django.db import models


class GalleryPage(models.Model):
    title = models.CharField(max_length=32, default="Галлерея")
    description = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to="images/gallery/main/")

class Image(models.Model):
    title = models.CharField(max_length=16)
    subtitle = models.CharField(max_length=64)
    image = models.ImageField(upload_to="images/gallery/")

apps/home/models.py
from django.db import models


class HomePage(models.Model):
    slogan = models.CharField(max_length=128, default="")
    title = models.CharField(max_length=128, default="")
    subtitle = models.CharField(max_length=128, default="")
    image = models.ImageField(upload_to="images/home/")

apps/services/models.py
from django.db import models


class Service(models.Model):
    icon = models.CharField(max_length=32, default="")
    title = models.CharField(max_length=32, default="")
    description = models.CharField(max_length=255, default="")
    show = models.BooleanField(default=True)


class ServicePage(models.Model):
    title = models.CharField(max_length=32, default="")
    description = models.CharField(max_length=255, default="")
    image = models.ImageField(upload_to="images/service/")

apps/about/views.py
from django.shortcuts import render

from apps.about.models import Review
from .models import AboutPage
from apps.utils import get_base_info

def about_page(request):
    context = {
        "page_name": "О Нас",
        "base_block": AboutPage.objects.last(),
        "reviews": Review.objects.all(),
    }
    context.update(get_base_info())
    return render(request, "pages/about.html", context)

apps/blog/views.py
from django.shortcuts import render, redirect
from apps.utils import get_base_info
from .models import BlogPage, Post, Comment


def blog_page(request):
    per_page = 12
    page = int(request.GET.get("page", 1))
    posts = Post.objects.all()
    posts_count = posts.count()
    context = {
        "page_name": "Блог",
        "base_block": BlogPage.objects.last(),
        "posts": posts.order_by("date")[(page - 1) * per_page: page * per_page],
        "pages": {_p: _p == page for _p in range(1, (posts_count // per_page) + (2 if posts_count % per_page else 1))},
    }
    context.update(get_base_info())
    return render(request, "pages/blog.html", context)

def post_view(request, id):
    context = {
        "page_name": "Блог",
        "post": Post.objects.get(id=id)
    }
    context.update(get_base_info())
    return render(request, "pages/blog-single.html", context)

def send_comment(request, id):
    post = Post.objects.get(id=id)
    comment = Comment.objects.create(
        name=request.POST.get("name"),
        email=request.POST.get("email"),
        site=request.POST.get("website"),
        message=request.POST.get("message"),
        post=post
    )
    return redirect("post_view", id)

apps/contact/views.py
from django.shortcuts import render

from .models import ContactPage
from apps.utils import get_base_info
from apps.about.models import Contacts

def contact_page(request):
    context = {
        "page_name": "Контакты",
        "base_block": ContactPage.objects.last(),
    }
    context.update(get_base_info())
    return render(request, "pages/contact.html", context)

apps/gallery/views.py
from django.shortcuts import render
from apps.utils import get_base_info
from .models import GalleryPage, Image


def gallery_page(request):
    context = {
        "page_name": "Галлерея",
        "base_block": GalleryPage.objects.last(),
        "images": Image.objects.all()
    }
    context.update(get_base_info())
    return render(request, "pages/gallery.html", context)

apps/home/views.py
from django.shortcuts import render

from .models import HomePage
from apps.services.models import ServicePage, Service
from apps.about.models import Review
from apps.blog.models import Post

from apps.utils import get_base_info


def home_page(request):
    context = {
        "page_name": "Главная",
        "home_page": HomePage.objects.last(),
        
        "service_page": ServicePage.objects.last(),
        "services": Service.objects.filter(show=True),
        "reviews": Review.objects.all(),
        "posts": Post.objects.all()[:3]
    }
    context.update(get_base_info())
    return render(request, "index.html", context)

apps/services/views.py
from django.shortcuts import render

from .models import ServicePage, Service
from apps.utils import get_base_info

def services_page(request):
    context = {
        "page_name": "Услуги",
        "base_block": ServicePage.objects.last(),
        "services": Service.objects.filter(show=True),
    }
    context.update(get_base_info())
    return render(request, "pages/services.html", context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>LawnCare - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>

    {% include 'components/header.html' %}

    {% block content %}
    <p>Нет контента.</p>
    {% endblock content %}

    {% include 'components/subscribe.html' %}

    {% include 'components/footer.html' %}

    
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

   <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
    </script>
    
  </body>
</html>

templates/components/base_block.html
<section class="hero-wrap hero-wrap-2" style="background-image: url('{{ base_block.image.url }}');" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{ page_name }}</h1>
                <p class="breadcrumbs">
                    <span class="mr-2">
                        <a href="{% url 'home_page' %}">Главная <i class="ion-ios-arrow-forward"></i></a>
                    </span>
                    <span>
                        {{ page_name }}
                        <i class="ion-ios-arrow-forward"></i>
                    </span>
                </p>
            </div>
        </div>
	</div>
</section>

templates/components/blog_block.html
<section class="ftco-section bg-light">
	<div class="container">
	<div class="row justify-content-center mb-5 pb-3">
		<div class="col-md-7 heading-section text-center ftco-animate">
            <span class="subheading">Наш Блог</span>
            <h2>Последние публикации</h2>
		</div>
	</div>
	<div class="row d-flex">

        {% for post in posts %}
		<div class="col-md-4 d-flex ftco-animate">
            <div class="blog-entry justify-content-end">
                <a href="{% url 'post_view' post.id %}" class="block-20" style="background-image: url('{{ post.image.url }}');">
                </a>
                <div class="text p-4 float-right d-block">
                <div class="topper d-flex align-items-center">
                    <div class="one py-2 pl-3 pr-1 align-self-stretch">
                        <span class="day">{{ post.date.day }}</span>
                    </div>
                    <div class="two pl-0 pr-3 py-2 align-self-stretch">
                        <span class="yr">{{ post.date.year }}</span>
                        <span class="mos">{{ post.date | date:"F" }}</span>
                    </div>
                </div>
                <h3 class="heading mb-0"><a href="#">{{ post.title }}</a></h3>
                <p>{{ post.description | truncatechars:150 }}</p>
                <p><a href="{% url 'post_view' post.id %}" class="btn btn-primary">Читать</a></p>
                </div>
            </div>
		</div>
        {% endfor %}

	</div>
	</div>
</section>

templates/components/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
	<div class="container">
	<div class="row mb-5">
		<div class="col-md-6 col-lg">
		<div class="ftco-footer-widget mb-4">
			<h2 class="logo"><a href="#">Южный <span>Парк</span></a></h2>
			<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
			<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
			<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
			<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
			</ul>
		</div>
		</div>
		<div class="col-md-6 col-lg">
		<div class="ftco-footer-widget mb-4 ml-md-5">
			<h2 class="ftco-heading-2">Services</h2>
			<ul class="list-unstyled">
			<li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Garden Care</a></li>
			<li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Lawn mowing</a></li>
			<li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Lawn Care</a></li>
			<li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Gutter Cleaning</a></li>
			<li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>New Lawn Installation</a></li>
			</ul>
		</div>
		</div>
		<div class="col-md-6 col-lg">
		<div class="ftco-footer-widget mb-4">
			<h2 class="ftco-heading-2">Contact information</h2>
			<div class="block-23 mb-3">
				<ul>
				<li><span class="icon icon-map-marker"></span><span class="text">{{ base_info.contacts.address }}</span></li>
				<li><a href="tel:{{ base_info.contacts.phone }}"><span class="icon icon-phone"></span><span class="text">{{ base_info.contacts.phone }}</span></a></li>
				<li><a href="mailto:{{ base_info.contacts.email }}"><span class="icon icon-envelope"></span><span class="text">{{ base_info.contacts.email }}</span></a></li>
				</ul>
			</div>
		</div>
		</div>
		<div class="col-md-6 col-lg">
			<div class="ftco-footer-widget mb-4">
			<h2 class="ftco-heading-2">Business Hours</h2>
			<div class="opening-hours">
			<h4>Рабочие дни:</h4>
			<p class="pl-3">
				<span>Понедельник – Пятница : 9:00 - 18:00</span>
				<span>Суббота : 9:00 - 16:00</span>
			</p>
			<h4>Выходные:</h4>
			<p class="pl-3">
				<span>Все Воскресные дни</span>
				<span>Все официальные праздники</span>
			</p>
			</div>
		</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center">

		<p>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены | Сайт сделан by <a href="https://miktadov.com" target="_blank">miktadov.com</a>
        </p>
		</div>
	</div>
	</div>
</footer>

templates/components/header.html
<div class="container pt-5 pb-4">
    <div class="row justify-content-between">
        <div class="col-md-8 order-md-last">
            <div class="row">
                <div class="col-md-6 text-center">
                    <a class="navbar-brand" href="index.html">Южный<span>Парк</span></a>
                </div>
                <div class="col-md-6 d-md-flex justify-content-end mb-md-0 mb-3">
                    <form action="#" class="searchform order-lg-last">
              <div class="form-group d-flex">
                <input type="text" class="form-control pl-3" placeholder="Поиск">
                <button type="submit" placeholder="" class="form-control search"><span class="fa fa-search"></span></button>
              </div>
            </form>
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex">
            <div class="social-media">
            <p class="mb-0 d-flex">
                <a href="{{ base_info.contacts.tg }}" class="d-flex align-items-center justify-content-center"><span class="fa fa-telegram"><i class="sr-only">Telegram</i></span></a>
                <a href="{{ base_info.contacts.wa }}" class="d-flex align-items-center justify-content-center"><span class="fa fa-whatsapp"><i class="sr-only">WhatsApp</i></span></a>
                <a href="tel:{{ base_info.contacts.phone }}" class="d-flex align-items-center justify-content-center"><span class="fa fa-phone"><i class="sr-only">Phone</i></span></a>
            </p>
    </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Меню
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav m-auto">
            <li class="nav-item {% if page_name == 'Главная' %}active{% endif %}"><a href="{% url 'home_page' %}" class="nav-link">Главная</a></li>
            <li class="nav-item {% if page_name == 'О Нас' %}active{% endif %}"><a href="{% url 'about_page' %}" class="nav-link">О Нас</a></li>
            <li class="nav-item {% if page_name == 'Услуги' %}active{% endif %}"><a href="{% url 'services_page' %}" class="nav-link">Услуги</a></li>
            <li class="nav-item {% if page_name == 'Галлерея' %}active{% endif %}"><a href="{% url 'gallery_page' %}" class="nav-link">Галлерея</a></li>
            <li class="nav-item {% if page_name == 'Блог' %}active{% endif %}"><a href="{% url 'blog_page' %}" class="nav-link">Блог</a></li>
            <li class="nav-item {% if page_name == 'Контакты' %}active{% endif %}"><a href="{% url 'contact_page' %}" class="nav-link">Контакты</a></li>
        </ul>
    </div>
    </div>
</nav>

templates/components/phone_line.html
<section class="ftco-intro bg-primary py-5">
	<div class="container">
		<div class="row justify-content-between align-items-center">
			<div class="col-md-6">
				<h2>Свяжитесь с нами</h2>
				<p>Если у вас есть какие-либо вопросы о продуктах, свяжитесь с нами.</p>
			</div>
			<div class="col-md-5 text-md-right">
				<span class="contact-number">{{ base_info.contacts.phone }}</span>
			</div>
		</div>
	</div>
</section>

templates/components/reviews.html
<section class="ftco-section testimony-section">
	<div class="container">
	<div class="row justify-content-center mb-5">
		<div class="col-md-7 text-center heading-section ftco-animate">
		<span class="subheading">Отзывы</span>
		<h2 class="mb-4">Наши счастливые Клиенты</h2>
		</div>
	</div>
	<div class="row ftco-animate">
		<div class="col-md-12">
            <div class="carousel-testimony owl-carousel ftco-owl">

                {% for review in reviews %}

                <div class="item">
                    <div class="testimony-wrap py-4">
                        <div class="text">
                            <p class="mb-4">{{ review.review }}</p>
                            <div class="d-flex align-items-center">
                                <div class="user-img" style="background-image: url('{{ review.image.url }}')"></div>
                                <div class="pl-3">
                                    <p class="name">{{ review.name }}</p>
                                    <span class="position">{{ review.position }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}
			
            </div>
		</div>
	</div>
	</div>
</section>

templates/components/seasons.html
{% load static %}
<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center mb-5">
            <div class="col-md-10 text-center heading-section ftco-animate">
                <span class="subheading">Всему свое время</span>
                <h2 class="mb-4">Сезоны и наша активность</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="carousel-seasonal owl-carousel ftco-owl">
                    <div class="item">
                        <div class="wrap">
                            <div class="seasonal img d-flex align-items-center justify-content-center" style="background-image: url({% static 'images/seasonal-2.jpg' %});"></div>
                            <div class="text text-center px-4">
                                <h3><a href="#">Лето</a></h3>
                                <p>Уход за растениями, поддержанию системы полива и борьба с вредителями. Это время для реализации и доработки проектов, а также для поддержания эстетической привлекательности.</p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="wrap">
                            <div class="seasonal img d-flex align-items-center justify-content-center" style="background-image: url({% static 'images/seasonal-4.jpg' %});"></div>
                            <div class="text text-center px-4">
                                <h3><a href="#">Осень</a></h3>
                                <p>Подготовка растений к зиме, посадка многолетников и луковичных, планирование изменений и улучшений для следующего года, включая выбор растений, которые будут высажены весной.</p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="wrap">
                            <div class="seasonal img d-flex align-items-center justify-content-center" style="background-image: url({% static 'images/seasonal-3.jpg' %});"></div>
                            <div class="text text-center px-4">
                                <h3><a href="#">Зима</a></h3>
                                <p>Проектирование новых ландшафтов и модификация существующих, подготовка предложений и дизайн-проектов для клиентов. Это время для обучения и профессионального развития.</p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="wrap">
                            <div class="seasonal img d-flex align-items-center justify-content-center" style="background-image: url({% static 'images/seasonal-1.jpg' %});"></div>
                            <div class="text text-center px-4">
                                <h3><a href="#">Весна</a></h3>
                                <p>Подготовка почвы и посадка растений, а также планирование новых проектов. В это время года происходит активное озеленение территорий и обновление ландшафтных композиций.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>

templates/components/services.html
<section class="ftco-section ftco-no-pt">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 py-5 order-md-last">
			<div class="heading-section ftco-animate">
			<span class="subheading">Наши услуги</span>
			<h2 class="mb-4">И многое другое</h2>
			<p>Помимо наиболее востребованных услуг мы предоставляем еще широкий спектр услуг по озеленению и ландшафтному дизайну как от самых маленьких объектов до больших государственных заказов.</p>
			<p><a href="#" class="btn btn-primary py-3 px-4">Узнать больше</a></p>
			</div>
			</div>
			<div class="col-lg-9 services-wrap px-4 pt-5">
				<div class="row pt-md-3">
					{% for service in services %}
					<div class="col-md-4 d-flex align-items-stretch">
						<div class="services text-center">
							<div class="icon d-flex justify-content-center align-items-center">
								<span class="{{ service.icon }}"></span>
							</div>
							<div class="text">
								<h3>{{ service.title }}</h3>
								<p>{{ service.description }}</p>
							</div>
							<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span class="ion-ios-arrow-round-forward"></span></a>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>

templates/components/subscribe.html
<section class="ftco-section ftco-no-pt ftco-no-pb bg-primary">
	<div class="container">
	<div class="row d-flex justify-content-center">
		<div class="col-lg-8 py-4">
			<div class="row">
				<div class="col-md-6 ftco-animate d-flex align-items-center">
				<h2 class="mb-0" style="color:white; font-size: 24px;">Подписаться на нашу расылку</h2>
				</div>
				<div class="col-md-6 d-flex align-items-center">
				<form action="#" class="subscribe-form">
					<div class="form-group d-flex">
					<input type="text" class="form-control" placeholder="Введите Ваш Email">
					<input type="submit" value="Subscribe" class="submit px-3">
					</div>
				</form>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>

templates/pages/about.html
{% extends "base.html" %}

{% block content %}

{% include 'components/base_block.html' %}

{% include 'components/video_block.html' %}

{% include 'components/phone_line.html' %}

{% include 'components/reviews.html' %}

{% endblock content %}

templates/pages/blog-single.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 ftco-animate">
          	<p>
              <img src="{{ post.image.url }}" alt="" class="img-fluid">
            </p>
            <h2 class="mb-3">{{ post.title }}</h2>
            <p style="white-space: pre-wrap;">{{ post.description }}</p>

            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">

                {% for tag in post.tags.all %}
                <a href="#" class="tag-cloud-link">{{ tag }}</a>
                {% endfor %}

              </div>
            </div>
            
            <h3>Автор статьи</h3>
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="{{ post.author.image.url }}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>{{ post.author.full_name }}</h3>
                <p>{{ post.author.description }}</p>
              </div>
            </div>


            <div class="pt-5 mt-5">
              <h3 class="mb-5">Комментарии <sub>{{ post.comment_set.count }}</sub></h3>
              <ul class="comment-list">

                {% for comment in post.comment_set.all %}
                <li class="comment">
                  <div class="vcard bio">
                    {% if comment.iamge %}
                      <img src="{{ comment.iamge.url }}" alt="Image placeholder">
                    {% else %}
                      <img src="{% static '/images/undefined_user.jpg' %}" alt="Image placeholder">
                    {% endif %}
                  </div>
                  <div class="comment-body">
                    <h3>{{ comment.name }}</h3>
                    <div class="meta">{{ comment.created_at }}</div>
                    <p>{{ comment.message }}</p>
                    <!-- <p><a href="#" class="reply">Reply</a></p> -->
                  </div>
                </li>
                {% endfor %}

              </ul>
              <!-- END comment-list -->
              
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Оставить комментарий</h3>

                <form action="{% url 'send_comment' post.id %}" method="POST" class="p-5 bg-light">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="name">Имя *</label>
                    <input name="name" type="text" class="form-control" id="name" required>
                  </div>
                  <div class="form-group">
                    <label for="email">Email *</label>
                    <input name="email" type="email" class="form-control" id="email" required>
                  </div>
                  <div class="form-group">
                    <label for="website">Сайт</label>
                    <input name="website" type="url" class="form-control" id="website">
                  </div>

                  <div class="form-group">
                    <label for="message">Комментарий</label>
                    <textarea name="message" id="message" cols="30" rows="10" class="form-control" required></textarea>
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Оставить комментарий" class="btn py-3 px-4 btn-primary">
                  </div>

                </form>

              </div>
            </div>

          </div> <!-- .col-md-8 -->

        </div>
      </div>
    </section>
{% endblock content %}

templates/pages/services.html
{% extends "base.html" %}

{% block content %}

{% include 'components/base_block.html' %}

{% include 'components/services.html' %}

{% include 'components/seasons.html' %}

{% endblock content %}